language: crystal

jobs:
  include:
    - stage: lint
      script: crystal tool format --check
    - stage: test
      script: crystal spec -v
    - stage: test-build
      script: make

notifications:
  email: false
